config/urls.py
from django.contrib import admin
from django.urls import path, include
from edu import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('edu/', include('edu.urls')),
    path('', views.index, name='index'),
]

edu/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


#namespace (네임스페이스)
app_name = 'edu'


urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('login/', auth_views.LoginView.as_view(template_name='edu/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

edu/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content

edu/forms.py
from django import forms
from .models import Question, Answer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields = ("username", "email")

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용'
       }

edu/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from .models import Question
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login
from .forms import UserForm


# Create your views here.
def index(request):

    question_list = Question.objects.order_by('create_date')
    # question_list = Question.objects.all()
    # question_list = Question.objects.filter(id=2)
    # question_list = Question.objects.filter(content__contains='장고')
    # question_list = Question.objects.get(id=2)

    try:
        # 모델의 데이터를 수정
        change = Question.objects.get(id=1)
        change.subject = '수정합니다.(첫번째 질문)'
        change.save()

        # 모델의 데이터 삭제
        dataDelete = Question.objects.get(id=1)
        dataDelete.delete()
    except(Question.DoesNotExist):
        print('Question 모델에 해당 데이터가 존재하지 않습니다.')

    # 모델에 데이터 추가
    # dataInsert = Question(subject="세번째 질문입니다.", content="언제 끝나나요?", create_date=timezone.now())
    # dataInsert.save()

    context = {
        'question_list': question_list,
        'name': '홍길동',
        'age': 25,
        'info': {
            'count': 10,
            'sort': 15,
        }
    }

    # 입력 파라미터
    # get방식 파라미터 : localhost:8000/pybo/?page=1
    page = request.GET.get('page', '1') #page 파라미터가 없을 경우
    # print('page :', page)

    # 페이징 처리
    # question_list를 페이지 객체로 변환
    paginator = Paginator(question_list, 10) #페이지당 10개씩 게시물
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}

    return render(request, 'edu/question_list.html', context)


def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}

    return render(request, 'edu/question_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())

    return redirect('edu:detail', question_id=question_id)


def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('edu:index')
    else:
        form = QuestionForm()

    context = {'form': form}

    return render(request, 'edu/question_form.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('edu:detail', question_id=question.id)
    else:
        form = AnswerForm()

    context = {'question': question, 'form': form}
    return render(request, 'edu/question_detail.html', context)


def signup(reqeust):
    if reqeust.method == "POST":
        form = UserForm(reqeust.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password = raw_password)
            login(reqeust, user)
            return redirect('index')
    else:
        form = UserForm()

    return render(request, 'edu/signup.html', {'form': form})

edu/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>기본 템플릿입니다.</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

edu/templates/edu/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <div>
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

edu/templates/edu/login.html
{% extends 'sub_base.html' %}

{% block content %}
<div class="container my-3">

    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div>
            <span>또는 <a href="{% url 'edu:signup' %}"> 계정을 만드세요. </a></span>
        </div>
    </div>

    <form action="{% url 'edu:login' %}" method="post">
        {% csrf_token %}
        {% include './form_errors.html' %}
        <div>
            <label for="username">사용자ID</label>
            <input type="text" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div>
            <label for="password">비밀번호</label>
            <input type="password" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit">로그인</button>
    </form>

</div>
{% endblock %}

edu/templates/edu/question_detail.html
{% extends 'sub_base.html' %}

{% block content %}

<h1>질문 제목과 내용입니다.</h1>

<h2>제목 : {{ question.subject }}</h2>

<div>
    내용 : {{ question.content}}
</div>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
            <li>{{ answer.content }}</li>
        {% endfor %}
    </ul>
</div>


<form action="{% url 'edu:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" rows="10"></textarea>
    <input type="submit" value="답변 등록">
</form>

{% endblock %}

edu/templates/edu/question_form.html
{% extends 'sub_base.html' %}

{% block content %}

<div>
    <h5>질문 등록</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장하기</button>
    </form>
</div>

{% endblock %}

edu/templates/edu/question_list.html
{% extends 'sub_base.html' %}
{% load edu_filter %}

{% block content %}

{% if user.is_authenticated %}
<a class="nav-link" href="{% url 'edu:logout' %}"> {{ user.username }} (로그아웃)</a>
{% else %}}
<a class="nav-link" href="{% url 'edu:login' %}">로그인</a>
{% endif %}

<h1>질문 목록입니다.</h1>

<div class="container my-3">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">번호</th>
            <th scope="col">제목</th>
            <th scope="col">작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 : 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}
            </td>
            <td>
                <a href="{% url 'edu:detail' question.id "> {{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3"> 질문 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

<!-- 페이징 처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전 페이지  -->
    {% if question_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">이전</a>
    </li>
    {% endif %}

    <!--  페이지 리스트  -->
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
    {% if page_number == question_list.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %}
    {% endfor %}

    <!--  다음 페이지지  -->
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
    </li>
    {% else %}}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">다음</a>
    </li>
    {% endif %}
</ul>
<!-- 페이징 처리 시작 -->

<a href="{% url 'edu:question_create' %}">질문 등록</a>

{% endblock %}

edu/templates/sub_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>서브 페이지 템플릿</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
상단 영역입니다. <br>
변경되었습니다.
<hr>

{% block content %}
{% endblock %}

<hr>
하단 영역입니다.
</body>
</html>